### ISSUE TITLE
Implement to_dict and from_dict for Command

### ISSUE THREAD

**Issue by afsafzal** [squaresLab/Houston#102]
If we want to store the missions generated, we need the `to_json` function to store them in json format and `from_json` to read them from file. Currently Command doesn't have `from_json`  function and the `to_json` function only creates a list of command's parameter values but it doesn't specify the kind of command.

**Comment by ChrisTimperley** [comment]
To fix this, we need to add a `type` property to command and state dictionaries. `from_dict` needs to know how to map between `type` and the corresponding `Command` subclass. Creating a mapping ios straightforward, but we need a way to uniquely identify `Command` subclasses. There are (at least) three ways to do this:

1. we use the `name` provided by the `Command` subclass as its unique identifier. I'm not a big fan of this since it could quickly lead to conflicts (if two systems both implement a `GoTo` command, for instance).
2. we add a new unique identifier property `uid` to the `Command` subclass. If users fail to provide a `uid`, one will be automatically generated in a deterministic fashion (see below).
3. we use the qualified name of the `Command` class as its type. This would make the dictionary a little ugly and harder to modify.

I think (2) is the way to go.

**Comment by afsafzal** [comment]
Yeah I think (2) is the best option. It could even be just a hash function of the name and parameters etc..

**Comment by ChrisTimperley** [comment]
Fixed by #103
